import { site, toolCards } from './config.mjs';

const cards = () => toolCards.map((card) => `
<article class="tool-card"><span class="badge">${card.badge}</span><h3><a href="${card.href}">${card.title}</a></h3><p>${card.description}</p></article>`).join('');

const faqHtml = (items=[]) => `<div class="faq">${items.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;
const crumbs = (label, href) => [{href:'/',label:'Home'},{href,label}];

const home = {
  path:'/',
  fontQuery:'family=Great+Vibes',
  title:`CursivePilot – Cursive, Handwriting & Calligraphy Tools`,
  description:'Free browser-based tools for copyable cursive text, handwriting pages, calligraphy lettering, signatures and printable handwriting worksheets.',
  content:`<section class="hero"><div class="shell hero-grid"><div><span class="eyebrow">Free browser-based writing tools</span><h1>Cursive, handwriting and calligraphy tools in one focused toolkit.</h1><p class="lede">Create copyable cursive text, handwriting-style pages, calligraphy artwork, signature previews and printable practice sheets. The core tools run in your browser and do not require an account.</p><div class="hero-actions"><a class="button button-primary" href="/cursive-generator/">Open Cursive Generator</a><a class="button button-secondary" href="/handwriting-generator/">Create Handwriting</a></div></div><div class="hero-art" aria-hidden="true"><div class="paper-stack"><div class="paper-sheet"></div><div class="paper-sheet"></div><div class="paper-sheet"><div class="script-demo">Write beautifully.</div><div class="script-sub">One focused toolkit for cursive, handwriting, calligraphy and practice.</div></div></div></div></div></section>
  <section class="section section-soft"><div class="shell"><div class="section-head"><h2>Choose what you want to make</h2><p>Each tool handles a distinct writing task: copyable Unicode text, rendered handwriting, decorative calligraphy, signature-style graphics or printable practice.</p></div><div class="tool-grid">${cards()}</div></div></section>
  <section class="section"><div class="shell content-grid"><article class="article"><h2>Copyable cursive, handwriting images and worksheets are different outputs</h2><p>Copyable cursive uses Unicode characters and remains text. Handwriting and calligraphy tools render exact visuals to a canvas for image export. Worksheets add guide rows for printable practice.</p><h2>Built for fast browser-side use</h2><p>The primary conversion and rendering work happens in your browser. That keeps the tools responsive and avoids sending every phrase to a remote handwriting service.</p><h2>Learn, compare and verify</h2><p>Use the <a href="/cursive-alphabet/">cursive alphabet</a> as an A–Z reference, the <a href="/cursive-text-compatibility/">compatibility checker</a> before pasting decorative Unicode into another app, or the <a href="/guides/unicode-cursive-vs-fonts/">Unicode cursive vs script fonts guide</a> when you need to understand the difference between text and visual font rendering.</p><h2>Use decorative text carefully</h2><p>Fancy Unicode can be useful for names, captions and short display text, but normal text is better for essential information and accessibility.</p></article><aside class="aside-card"><h2>Explore</h2><a href="/cursive-generator/">Cursive generator</a><a href="/handwriting-generator/">Handwriting generator</a><a href="/calligraphy-generator/">Calligraphy generator</a><a href="/signature-generator/">Signature generator</a><a href="/handwriting-worksheet-generator/">Worksheet generator</a></aside></div></section>`
};

const cursiveFaq=[
 ['What is a cursive generator?','It converts ordinary letters into script-like Unicode characters that can be copied and pasted as text.'],
 ['Can I copy the result?','Yes. The main cursive styles remain Unicode text, although appearance can vary by device.'],
 ['Is this a downloadable font file?','No. The copyable output is Unicode text rather than a TTF or OTF font.'],
 ['Is a cursive translator the same thing?','People sometimes use “cursive translator” to mean changing normal text into a cursive style. This tool changes letter style only; it does not translate between languages.']
];
const cursive={
 path:'/cursive-generator/',type:'tool',script:'/assets/unicode.js',
 title:`Cursive Generator – Copy & Paste Cursive Text | ${site.name}`,
 description:'Free cursive generator and cursive font generator for copy-and-paste script text. Search styles, save favorites and copy instantly.',
 features:['Copyable Unicode cursive text','Searchable style library','Favorite styles stored locally','One-click copy','Shareable links','Browser-side conversion'],
 breadcrumbs:crumbs('Cursive Generator','/cursive-generator/'),faqs:cursiveFaq,
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Copyable Unicode text</span><h1>Cursive Generator</h1><p class="lede">Turn normal text into copy-and-paste cursive styles for names, bios, captions and messages. Search the style library, save favorites on this device and copy any result in one click.</p></div><div class="tool-panel" data-unicode-tool><div class="tool-panel-head"><h2>Convert text to cursive</h2><span class="privacy-note">● Runs in your browser</span></div><div class="tool-body"><div class="field"><label for="cursive-input">Your text</label><textarea id="cursive-input" data-input maxlength="500">Write beautifully</textarea><div class="control-row"><span class="helper" data-counter>0 / 500</span><button class="button button-secondary button-small" type="button" data-example>Example</button><button class="button button-secondary button-small" type="button" data-clear>Clear</button><button class="button button-ghost button-small" type="button" data-share>Copy share link</button></div></div><div class="style-toolbar"><div class="field"><label for="style-search">Search styles</label><input id="style-search" data-style-search type="text" placeholder="Try cursive, gothic, modern…"></div><div class="field"><label for="style-category">Category</label><select id="style-category" data-style-category><option>All</option><option>Cursive</option><option>Classic</option><option>Modern</option><option>Gothic</option><option>Decorative</option></select></div><div class="filter-actions"><label class="favorite-filter"><input type="checkbox" data-favorites-only> Favorites only</label><button class="button button-secondary button-small" type="button" data-reset-filters>Reset filters</button></div></div><div class="style-summary"><span data-style-count></span><span>Favorites stay only in this browser.</span></div><p class="status" data-status aria-live="polite"></p><div class="unicode-results" data-results></div></div></div></div></section>
 <section class="section section-soft"><div class="shell"><div class="section-head"><h2>Static cursive examples</h2><p>Compare plain text with several Unicode styles before you type anything, then use the generator above to create and copy your own version.</p></div><div class="example-grid"><div class="example-card"><strong>Plain</strong><span>Cursive Pilot</span></div><div class="example-card"><strong>Script</strong><span>𝒞𝓊𝓇𝓈𝒾𝓋ℯ 𝒫𝒾𝓁ℴ𝓉</span></div><div class="example-card"><strong>Bold Script</strong><span>𝓒𝓾𝓻𝓼𝓲𝓿𝓮 𝓟𝓲𝓵𝓸𝓽</span></div><div class="example-card"><strong>Italic</strong><span>𝐶𝑢𝑟𝑠𝑖𝑣𝑒 𝑃𝑖𝑙𝑜𝑡</span></div></div></div></section>
 <section class="section"><div class="shell content-grid"><article class="article"><h2>What a cursive text generator actually changes</h2><p>CursivePilot works as a cursive font generator for copy-and-paste text by replacing many ordinary Latin letters with visually similar Unicode characters. The output remains text, not an uploaded image.</p><p>The appearance is controlled by the receiving device and its fonts, so the same Unicode string can look slightly different on another phone, browser or app. If exact visual appearance matters, use the <a href="/handwriting-generator/">handwriting generator</a> or <a href="/calligraphy-generator/">calligraphy generator</a> and export an image instead.</p><h2>Choose a style by purpose, not just appearance</h2><p>Script and bold-script styles are the closest match to what most people mean by cursive text. Italic and modern styles are cleaner. Gothic, circled and fullwidth styles are more decorative and may be less readable. Essential information should stay in ordinary characters.</p><h2>Will cursive text work in every app?</h2><p>No generator can guarantee identical support everywhere. Use our <a href="/cursive-text-compatibility/">Cursive Text Compatibility Lab</a> to create a test string, then paste it into the actual app and device you care about.</p><h2>Is this a cursive font generator or an actual font file?</h2><p>This cursive font generator creates Unicode-style text rather than a downloadable TTF or OTF file. Unicode text is best when copyability matters. A real font changes how normal characters are drawn. Our <a href="/guides/unicode-cursive-vs-fonts/">Unicode cursive vs. script fonts guide</a> explains the tradeoffs.</p><h2>FAQ</h2>${faqHtml(cursiveFaq)}</article><aside class="aside-card"><h2>Related tools</h2><a href="/cursive-text-compatibility/">Compatibility Lab</a><a href="/handwriting-generator/">Handwriting generator</a><a href="/calligraphy-generator/">Calligraphy generator</a><a href="/signature-generator/">Signature generator</a></aside></div></section>`
};

const handwritingFaq=[
 ['What does the handwriting generator create?','It renders typed text onto a handwriting-style page using selectable script fonts, spacing and paper settings.'],
 ['Can I download it?','Yes. Download the page currently shown as PNG or use Print / Save PDF for all rendered pages.'],
 ['Does it clone real handwriting?','No. This version uses script fonts and natural variation rather than copying a person’s biometric handwriting.']
];
const handwriting={
 path:'/handwriting-generator/',type:'tool',script:'/assets/handwriting.js',
 fontQuery:'family=Caveat:wght@400..700&family=Dancing+Script:wght@400..700&family=Homemade+Apple&family=Kalam:wght@300;400;700&family=Patrick+Hand&family=Satisfy',
 title:`Handwriting Generator – Text to Handwriting | ${site.name}`,
 description:'Free handwriting generator for turning typed text into handwriting-style PNG pages or printable PDFs with paper, ink and spacing controls.',
 features:['Text to handwriting-style page','Multiple script styles','Paper and ink controls','PNG download','Print/PDF workflow'],
 breadcrumbs:crumbs('Handwriting Generator','/handwriting-generator/'),faqs:handwritingFaq,
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Text to handwriting</span><h1>Handwriting Generator</h1><p class="lede">Use this free handwriting generator to turn typed text into a handwriting-style page, customize the paper and ink, and export the result as PNG or PDF.</p></div><div class="tool-panel" data-handwriting-tool><div class="tool-panel-head"><h2>Create a handwriting page</h2><span class="privacy-note">● Rendering happens locally</span></div><div class="tool-body"><div class="canvas-layout"><div class="settings-panel">
 <div class="field field-full"><label for="hw-text">Text</label><textarea id="hw-text" data-text maxlength="6000">Dear friend,

A handwritten note can make a simple message feel more personal.</textarea><span class="helper">Up to 6,000 characters. Normal input is rendered across as many pages as needed; unusually page-heavy input shows an explicit safe-limit warning instead of silently truncating.</span></div>
 <div class="field"><label for="hw-font">Style</label><select id="hw-font" data-font><option>Dancing Script</option><option>Caveat</option><option>Kalam</option><option>Patrick Hand</option><option>Homemade Apple</option><option>Satisfy</option></select></div>
 <div class="field"><label for="hw-paper">Paper</label><select id="hw-paper" data-paper><option value="notebook">Notebook</option><option value="lined">Lined</option><option value="warm">Warm paper</option><option value="plain">Plain</option><option value="grid">Grid</option></select></div>
 <div class="field"><label for="hw-page">Page size</label><select id="hw-page" data-page-size><option value="a4">A4</option><option value="letter">US Letter</option></select></div>
 <div class="field"><label for="hw-ink">Ink color</label><input id="hw-ink" data-ink type="color" value="#173765"></div>
 <div class="field"><label for="hw-size">Font size</label><input id="hw-size" data-font-size type="range" min="24" max="54" value="34"></div>
 <div class="field"><label for="hw-line">Line height</label><input id="hw-line" data-line-height type="range" min="38" max="74" value="52"></div>
 <div class="field"><label for="hw-var">Natural variation</label><input id="hw-var" data-variation type="range" min="0" max="1" step="0.05" value="0.45"></div>
 <div class="control-row field-full"><button class="button button-primary" type="button" data-download-png>Download current page PNG</button><button class="button button-secondary" type="button" data-print>Print / Save all pages PDF</button></div><p class="status field-full" data-status></p></div>
 <div class="worksheet-preview-wrap"><div class="worksheet-preview-toolbar" aria-label="Handwriting page navigation"><button class="button button-secondary button-small" type="button" data-prev-page>← Previous</button><strong data-page-indicator>Page 1 of 1</strong><button class="button button-secondary button-small" type="button" data-next-page>Next →</button></div><div class="preview-stage" data-preview></div><p class="preview-caption" data-preview-caption></p></div></div></div></div></div></section>
 <section class="section"><div class="shell content-grid"><article class="article"><h2>Text to handwriting without uploading every phrase</h2><p>The text-to-handwriting renderer works in the browser. Choose a handwriting style, notebook or plain paper, ink color, font size, line spacing and natural variation, then review the live page before exporting it.</p><h2>PNG or PDF: choose the output that fits the job</h2><p>PNG is useful for a single page you want to place into a design or share as an image. Print / Save PDF is better for multi-page text because the browser print flow includes every generated page.</p><h2>Handwriting generator vs. copyable cursive text</h2><p>A handwritten text generator preserves a visual page layout, while the <a href="/cursive-generator/">cursive generator</a> creates Unicode characters that remain copyable text. If you are looking for a cursive writing generator with a paper-style image result, this page is the better fit.</p><h2>What this text to handwriting converter does not do</h2><p>It does not identify, authenticate or imitate a specific person's handwriting. The styles are based on selectable fonts plus small rendering variation. Review every generated page before using it in important work.</p><h2>FAQ</h2>${faqHtml(handwritingFaq)}</article><aside class="aside-card"><h2>Related</h2><a href="/cursive-generator/">Copyable cursive</a><a href="/handwriting-worksheet-generator/">Worksheets</a><a href="/calligraphy-generator/">Calligraphy</a></aside></div></section>`
};

const calligraphyFaq=[
 ['Can I create a transparent PNG?','Yes. Enable transparent background before downloading.'],
 ['Is calligraphy output copyable text?','No. The calligraphy preview is rendered as an image so its exact visual style is preserved.']
];
const calligraphy={
 path:'/calligraphy-generator/',type:'tool',script:'/assets/calligraphy.js',
 fontQuery:'family=Allura&family=Dancing+Script:wght@400..700&family=Great+Vibes&family=Pacifico&family=Sacramento&family=Satisfy',
 title:`Calligraphy Generator – Text to Calligraphy | ${site.name}`,
 description:'Free calligraphy generator for turning text into decorative script lettering. Choose a style, colors and size, then download a transparent PNG.',
 features:['Multiple script fonts','Ink and background controls','Transparent PNG export','Browser-side rendering'],
 breadcrumbs:crumbs('Calligraphy Generator','/calligraphy-generator/'),faqs:calligraphyFaq,
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Visual lettering</span><h1>Calligraphy Generator</h1><p class="lede">Use this free calligraphy generator to turn text into decorative script lettering for names, invitations, quotes and design mockups.</p></div><div class="tool-panel" data-calligraphy-tool><div class="tool-panel-head"><h2>Design your calligraphy</h2><span class="privacy-note">● Runs in your browser</span></div><div class="tool-body"><div class="canvas-layout"><div class="settings-panel">
 <div class="field field-full"><label for="cal-text">Text</label><textarea id="cal-text" data-text maxlength="400">Beautiful words</textarea></div>
 <div class="field"><label for="cal-font">Style</label><select id="cal-font" data-font><option>Great Vibes</option><option>Allura</option><option>Sacramento</option><option>Satisfy</option><option>Pacifico</option><option>Dancing Script</option></select></div>
 <div class="field"><label for="cal-size">Text size</label><input id="cal-size" data-font-size type="range" min="54" max="160" value="104"></div>
 <div class="field"><label for="cal-ink">Ink</label><input id="cal-ink" data-ink type="color" value="#17382f"></div>
 <div class="field"><label for="cal-bg">Background</label><input id="cal-bg" data-bg type="color" value="#fffdf8"></div>
 <label class="field"><span class="label">Transparent background</span><input data-transparent type="checkbox"></label>
 <div class="control-row field-full"><button class="button button-primary" type="button" data-download>Download PNG</button></div><p class="status field-full" data-status></p></div>
 <div><div class="preview-stage" data-preview></div><p class="preview-caption">Transparent export works well for design overlays.</p></div></div></div></div></div></section>
 <section class="section"><div class="shell content-grid"><article class="article"><h2>A calligraphy text generator for visual lettering</h2><p>The calligraphy text generator renders your words as an image so the chosen script appearance stays consistent when you download it. Adjust the typeface, text size, ink color and background before export.</p><h2>When to use a transparent PNG</h2><p>Transparent output is useful when you want to place calligraphy over an invitation, presentation, social graphic or other design. Use a solid background when the lettering is the finished image itself.</p><h2>Calligraphy generator vs. cursive copy-and-paste text</h2><p>Calligraphy on this page is visual artwork. If you need text that remains copyable in another app, use the <a href="/cursive-generator/">cursive generator</a> instead. If you are styling a person's name like a decorative signature, the <a href="/signature-generator/">cursive signature generator</a> is more focused on that task.</p><h2>Use script styles for decoration, not identity verification</h2><p>The output is decorative lettering. It does not authenticate handwriting, ownership or a legal signature.</p><h2>FAQ</h2>${faqHtml(calligraphyFaq)}</article><aside class="aside-card"><h2>Related</h2><a href="/cursive-generator/">Cursive text</a><a href="/signature-generator/">Signature generator</a><a href="/handwriting-generator/">Handwriting generator</a></aside></div></section>`
};

const signatureFaq=[
 ['Does this create a legal signature?','It creates a visual signature-style name preview. It does not determine legal validity.'],
 ['Can I download a transparent PNG?','Yes. The exported canvas uses a transparent background.']
];
const signature={
 path:'/signature-generator/',type:'tool',script:'/assets/signature.js',
 fontQuery:'family=Allura&family=Great+Vibes&family=Sacramento&family=Satisfy',
 title:`Cursive Signature Generator & Name Maker | ${site.name}`,
 description:'Free cursive signature generator for previewing a name in script styles and downloading a transparent PNG for personal design use.',
 features:['Cursive name previews','Multiple script fonts','Ink color control','Underline flourish','Transparent PNG export'],
 breadcrumbs:crumbs('Cursive Signature Generator','/signature-generator/'),faqs:signatureFaq,
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Names & signature-style lettering</span><h1>Cursive Signature Generator</h1><p class="lede">Enter a name, compare script styles and use this cursive signature generator to download a transparent signature-style PNG.</p></div><div class="tool-panel" data-signature-tool><div class="tool-panel-head"><h2>Preview your name</h2><span class="privacy-note">● Rendered locally</span></div><div class="tool-body">
 <div class="input-grid"><div class="field field-full"><label for="sig-name">Name</label><input id="sig-name" data-name type="text" maxlength="60" value="Alex Morgan"></div><div class="field"><label for="sig-ink">Ink</label><input id="sig-ink" data-ink type="color" value="#17382f"></div><label class="field"><span class="label">Add underline flourish</span><input data-underline type="checkbox" checked></label></div>
 <div class="signature-grid">
 <button class="signature-card" type="button" data-signature-card data-font="Great Vibes"><span class="signature-name" data-card-name style="font-family:'Great Vibes',cursive"></span><span class="signature-meta">Great Vibes</span></button>
 <button class="signature-card" type="button" data-signature-card data-font="Allura"><span class="signature-name" data-card-name style="font-family:Allura,cursive"></span><span class="signature-meta">Allura</span></button>
 <button class="signature-card" type="button" data-signature-card data-font="Sacramento"><span class="signature-name" data-card-name style="font-family:Sacramento,cursive"></span><span class="signature-meta">Sacramento</span></button>
 <button class="signature-card" type="button" data-signature-card data-font="Satisfy"><span class="signature-name" data-card-name style="font-family:Satisfy,cursive"></span><span class="signature-meta">Satisfy</span></button>
 </div><div class="preview-stage" data-preview style="min-height:250px;margin-top:18px"></div><div class="control-row" style="margin-top:14px"><button class="button button-primary" type="button" data-download>Download transparent PNG</button></div><p class="status" data-status></p></div></div></div></section>
 <section class="section"><div class="shell content-grid"><article class="article"><h2>A cursive name generator for decorative signature styles</h2><p>This page also works as a cursive name generator: type a name once, compare several script faces, change the ink and add or remove the underline flourish before downloading the image.</p><h2>Signature generator output is an image, not identity proof</h2><p>The transparent PNG is useful for personal graphics, mockups, invitations, profile artwork and similar design tasks. It is not a handwriting-signature verification service and does not prove that a person signed or approved a document.</p><h2>How this differs from a handwriting generator</h2><p>The <a href="/handwriting-generator/">handwriting generator</a> is designed for paragraphs and page layouts. This signature generator is optimized for a short name-style mark. For copyable Unicode rather than an image, use the <a href="/cursive-generator/">cursive text generator</a>.</p><h2>Choose a readable style</h2><p>Highly decorative script can become difficult to read at small sizes. Preview the downloaded image at the size where you plan to use it and simplify the flourish if the name becomes unclear.</p><h2>FAQ</h2>${faqHtml(signatureFaq)}</article><aside class="aside-card"><h2>Related</h2><a href="/calligraphy-generator/">Calligraphy</a><a href="/cursive-generator/">Cursive text</a><a href="/handwriting-generator/">Handwriting</a></aside></div></section>`
};

const worksheetFaq=[
 ['Can I add a student name and date?','Yes. Both are optional. If provided, they appear in the worksheet header. The date defaults to today and can be changed or cleared.'],
 ['What does Trace + Practice do?','The first row contains faint tracing text and the remaining rows stay blank for independent practice, avoiding unnecessary repeated dark examples.'],
 ['Can I make more than one page?','Yes. Add one practice item per line. Use Previous and Next to inspect every generated page, then Print / Save PDF to save all pages together.'],
 ['Can I download a PNG?','Yes. The PNG button downloads the page currently visible in the preview. Print / Save PDF includes every generated page.']
];
const worksheet={
 path:'/handwriting-worksheet-generator/',type:'tool',script:'/assets/worksheet.js',
 fontQuery:'family=Caveat:wght@400..700&family=Dancing+Script:wght@400..700&family=Homemade+Apple&family=Kalam:wght@300;400;700&family=Patrick+Hand&family=Satisfy',
 title:`Handwriting Worksheet Generator | ${site.name}`,
 description:'Free handwriting worksheet generator for custom cursive or print practice sheets with trace-and-practice rows, page previews, PNG and PDF export.',
 features:['Custom practice phrases','Optional student name and date','Cursive or print writing','Multiple handwriting styles','Trace and independent practice modes','2 to 4 rows per item','Multi-page preview','PNG and print/PDF export'],
 breadcrumbs:crumbs('Worksheet Generator','/handwriting-worksheet-generator/'),faqs:worksheetFaq,
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Printable practice</span><h1>Handwriting Worksheet Generator</h1><p class="lede">Create clean handwriting practice sheets from your own names, words or sentences. Add optional student details, choose cursive or print, and preview every page before printing.</p></div><div class="tool-panel" data-worksheet-tool><div class="tool-panel-head"><h2>Build a practice worksheet</h2><span class="privacy-note">● Runs locally</span></div><div class="tool-body"><div class="canvas-layout"><div class="settings-panel">
 <div class="field field-full"><label for="ws-title">Worksheet title</label><input id="ws-title" data-title type="text" maxlength="50" value="Handwriting Practice"></div>
 <div class="field"><label for="ws-student">Student name <span class="helper">(optional)</span></label><input id="ws-student" data-student-name type="text" maxlength="60" placeholder="e.g. Alex Smith"></div>
 <div class="field"><label for="ws-date">Date <span class="helper">(optional)</span></label><input id="ws-date" data-date type="date"></div>
 <div class="field field-full"><label for="ws-text">Practice text — one item per line</label><textarea id="ws-text" data-text maxlength="2500">Beautiful writing
Practice makes progress
Slow and steady
The quick brown fox</textarea><span class="helper">Up to 24 practice items. Each non-empty line becomes one worksheet item.</span></div>
 <div class="field"><label for="ws-script">Writing type</label><select id="ws-script" data-script><option value="cursive">Cursive</option><option value="print">Print</option></select></div>
 <div class="field"><label for="ws-font">Handwriting style</label><select id="ws-font" data-font></select></div>
 <div class="field"><label for="ws-mode">Practice mode</label><select id="ws-mode" data-mode><option value="mixed" selected>Trace + Practice</option><option value="trace">Trace every row</option><option value="copy">Copy from model</option></select></div>
 <div class="field"><label for="ws-rows">Rows per item</label><select id="ws-rows" data-rows><option value="2">2 rows</option><option value="3" selected>3 rows</option><option value="4">4 rows</option></select></div>
 <div class="field"><label for="ws-page">Page size</label><select id="ws-page" data-page-size><option value="letter">US Letter</option><option value="a4">A4</option></select></div>
 <div class="control-row field-full"><button class="button button-primary" type="button" data-download-png>Download current page PNG</button><button class="button button-secondary" type="button" data-print>Print / Save all pages PDF</button></div>
 <p class="status field-full" data-status aria-live="polite"></p></div>
 <div class="worksheet-preview-wrap">
  <div class="worksheet-preview-toolbar" aria-label="Worksheet page navigation">
   <button class="button button-secondary button-small" type="button" data-prev-page>← Previous</button>
   <strong data-page-indicator>Page 1 of 1</strong>
   <button class="button button-secondary button-small" type="button" data-next-page>Next →</button>
  </div>
  <div class="preview-stage" data-preview></div>
  <p class="preview-caption" data-preview-caption></p>
 </div></div></div></div></div></section>
 <section class="section"><div class="shell content-grid"><article class="article"><h2>Build a worksheet that separates tracing from independent writing</h2><p>The default <strong>Trace + Practice</strong> mode gives each item one faint tracing row followed by blank rows. That keeps the model visible without printing the same phrase repeatedly in dark handwriting.</p><h2>Add your own student details</h2><p>Student name and date are optional. If you fill them in, they appear in the worksheet header. If the name is left blank, the worksheet keeps a blank line so it can be completed by hand.</p><h2>Preview every generated page</h2><p>Longer lists automatically create more pages. Use Previous and Next to inspect each page. PNG export saves the page currently shown, while Print / Save PDF includes the entire worksheet.</p><h2>Choose cursive or print</h2><p>Cursive includes several script-style options, while Print uses more separated handwriting forms. Choose Cursive when you want a cursive handwriting worksheet generator and Print for non-joined practice. The result is designed for general practice and is not tied to one school handwriting curriculum.</p><h2>FAQ</h2>${faqHtml(worksheetFaq)}</article><aside class="aside-card"><h2>Related</h2><a href="/cursive-alphabet/">Cursive alphabet</a><a href="/guides/how-to-practice-cursive/">Practice guide</a><a href="/handwriting-generator/">Handwriting generator</a></aside></div></section>`
};

const alphabetLetters=[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].map((letter)=>`<div class="alpha-card"><div class="alpha-script">${letter}${letter.toLowerCase()}</div><div class="alpha-plain">${letter} ${letter.toLowerCase()}</div></div>`).join('');
const alphabet={
 path:'/cursive-alphabet/',fontQuery:'family=Dancing+Script:wght@400..700',
 title:`Cursive Alphabet A–Z: Uppercase & Lowercase | ${site.name}`,
 description:'Cursive alphabet A to Z reference with uppercase and lowercase cursive letters, plus links to copyable cursive text and printable practice worksheets.',
 breadcrumbs:crumbs('Cursive Alphabet','/cursive-alphabet/'),
 content:`<section class="section"><div class="shell"><div class="tool-intro"><span class="eyebrow">A–Z reference</span><h1>Cursive Alphabet A–Z</h1><p class="lede">Review uppercase and lowercase cursive letters from A to Z, then move from individual letter shapes into words and printable practice.</p></div><div class="alpha-grid">${alphabetLetters}</div></div></section><section class="section"><div class="shell content-grid"><article class="article"><h2>Uppercase and lowercase cursive letters</h2><p>The grid above pairs each capital letter with its lowercase form. It is a visual reference, not a claim that one digital font represents every school or handwriting method. Cursive letterforms can vary by curriculum, country and personal writing style.</p><h2>How to use this cursive alphabet reference</h2><p>Start by comparing a few letters at a time, especially shapes that change noticeably between uppercase and lowercase. Then practice those letters inside familiar names or short words instead of treating the alphabet as isolated symbols.</p><h2>Copy cursive letters or practice writing them</h2><p>If you want copyable Unicode characters for a name or caption, use the <a href="/cursive-generator/">cursive generator</a>. If you want lines to trace and write by hand, use the <a href="/handwriting-worksheet-generator/">handwriting worksheet generator</a> and choose Cursive as the writing type.</p><h2>Cursive alphabet styles are not identical everywhere</h2><p>Font shapes are only examples. A teacher, handwriting program or regional style may form capitals, joins and loops differently. Use the reference that matches the method you are actually learning.</p></article><aside class="aside-card"><h2>Practice next</h2><a href="/cursive-generator/">Cursive generator</a><a href="/handwriting-worksheet-generator/">Worksheet generator</a><a href="/guides/how-to-practice-cursive/">How to practice cursive</a></aside></div></section>`
};

const guideUnicode={
 path:'/guides/unicode-cursive-vs-fonts/',type:'guide',published:'2026-09-27',modified:'2026-09-27',
 title:`Unicode Cursive vs Script Fonts | ${site.name}`,
 description:'Understand the difference between copyable Unicode cursive, script fonts and rendered handwriting images, including compatibility and accessibility tradeoffs.',
 breadcrumbs:crumbs('Unicode Cursive vs Fonts','/guides/unicode-cursive-vs-fonts/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><span class="eyebrow">Practical guide</span><h1>Unicode cursive vs. script fonts</h1><p class="lede">They can look similar on screen, but they behave differently when you copy, paste, search, edit or export them.</p><p class="article-meta">Published and reviewed by CursivePilot Editorial · September 27, 2026</p><h2>The short version</h2><table><thead><tr><th>Method</th><th>What is stored</th><th>Best for</th></tr></thead><tbody><tr><td>Unicode cursive</td><td>Special Unicode characters</td><td>Copy-and-paste display text</td></tr><tr><td>Script font</td><td>Normal letters + font choice</td><td>Designs and webpages</td></tr><tr><td>Rendered image</td><td>Pixels</td><td>Preserving an exact visual appearance</td></tr></tbody></table><h2>What Unicode cursive is</h2><p>A Unicode cursive generator substitutes many ordinary Latin letters with characters from Unicode blocks that include mathematical script, italic and other styled alphabets. The result is still text.</p><h2>Why the same text can look different</h2><p>Unicode defines characters, but the operating system or app still chooses the font used to draw them. A different fallback font can change stroke shape, spacing or weight, and missing glyphs can appear as boxes.</p><h2>How script fonts differ</h2><p>A script font keeps ordinary text characters and changes only the visual glyph design. Exact appearance is preserved only where that font is available, so PNG or PDF export is safer when appearance must not change.</p><h2>Accessibility and search</h2><p>Decorative Unicode can reduce readability and may be announced unexpectedly by assistive technologies. Search, moderation and username systems can also treat visually similar Unicode differently from ordinary letters. Keep important information in normal text.</p><h2>How to test compatibility</h2><ol><li>Create a short sample in the <a href="/cursive-generator/">Cursive Generator</a>.</li><li>Open the real destination app.</li><li>Paste the sample into the exact field you plan to use.</li><li>Check for missing glyphs, broken spacing and readability.</li><li>If support is poor, use a simpler style or an exported image.</li></ol><p>Our <a href="/cursive-text-compatibility/">Compatibility Lab</a> makes this process quicker without pretending one browser preview can certify every platform.</p><h2>When to choose each format</h2><p>Choose Unicode when copyability matters, a script font when you control the design environment, and an image when you need the same visual result everywhere.</p></article><aside class="aside-card"><h2>Try the tools</h2><a href="/cursive-generator/">Cursive generator</a><a href="/cursive-text-compatibility/">Compatibility Lab</a><a href="/handwriting-generator/">Handwriting generator</a></aside></div></section>`
};

const guidePractice={
 path:'/guides/how-to-practice-cursive/',type:'guide',published:'2026-09-27',modified:'2026-09-27',
 title:`How to Practice Cursive | Printable Routine | ${site.name}`,
 description:'Cursive practice guide with a simple trace-copy-write routine, printable worksheet tips and links to custom handwriting practice tools.',
 breadcrumbs:crumbs('How to Practice Cursive','/guides/how-to-practice-cursive/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><span class="eyebrow">Practice guide</span><h1>How to practice cursive with short, focused worksheets</h1><p class="lede">A simple worksheet works best when it gives you one small target at a time instead of a crowded page.</p><p class="article-meta">Published and reviewed by CursivePilot Editorial · September 27, 2026</p><h2>A simple trace-copy-write routine</h2><ol><li><strong>Choose one target.</strong> Use a name, one letter join or a short sentence.</li><li><strong>Trace it slowly.</strong> Pay attention to starting points, joins and spacing.</li><li><strong>Copy it while looking at the model.</strong> Keep the same baseline and approximate spacing.</li><li><strong>Write it independently.</strong> Hide or move away from the model for one attempt.</li><li><strong>Compare for legibility.</strong> Circle one thing to improve on the next line rather than correcting everything at once.</li></ol><h2>Start with words you actually use</h2><p>Names, days of the week, school subjects and short everyday phrases can be easier to stay engaged with than random letter strings. The <a href="/handwriting-worksheet-generator/">Handwriting Worksheet Generator</a> lets you enter your own phrases, choose cursive or print, and create trace, copy or mixed practice rows.</p><h2>Use the alphabet as a reference, not a score</h2><p>Letterforms vary across handwriting methods and typefaces. Use the <a href="/cursive-alphabet/">Cursive Alphabet</a> page as a visual reference, then focus on consistency and readability rather than matching one digital font perfectly.</p><h2>Printing checklist</h2><ul><li>Choose A4 or US Letter to match your printer paper.</li><li>Open Print / Save PDF and check the preview before printing.</li><li>Avoid browser scaling that makes guide lines too small.</li><li>Use a comfortable writing size rather than fitting too much on one page.</li></ul><div class="callout"><strong>Note:</strong> This is a general practice workflow, not an occupational-therapy or medical recommendation.</div></article><aside class="aside-card"><h2>Practice tools</h2><a href="/handwriting-worksheet-generator/">Worksheet generator</a><a href="/cursive-alphabet/">Cursive alphabet</a><a href="/cursive-generator/">Cursive generator</a></aside></div></section>`
};

const compatibility={
 path:'/cursive-text-compatibility/',type:'tool',script:'/assets/compatibility.js',
 title:`Cursive Text Compatibility Checker | ${site.name}`,
 description:'Test cursive text compatibility by generating Unicode styles, previewing layout sizes and copying the exact string into the real app or device you use.',
 features:['Unicode test string','Multiple cursive styles','Copy for real-device testing','Browser preview layouts','No account required'],
 breadcrumbs:crumbs('Cursive Text Compatibility Checker','/cursive-text-compatibility/'),
 content:`<section class="tool-shell"><div class="shell"><div class="tool-intro"><span class="eyebrow">Real-world copy/paste testing</span><h1>Cursive Text Compatibility Checker</h1><p class="lede">Use this cursive text compatibility checker to create a repeatable Unicode test string, then paste that exact text into the real app or device you care about.</p></div><div class="tool-panel" data-compatibility-lab><div class="tool-panel-head"><h2>Create a compatibility test</h2><span class="privacy-note">● Runs in your browser</span></div><div class="tool-body"><div class="input-grid"><div class="field"><label for="compat-text">Test text</label><input id="compat-text" data-compat-input type="text" maxlength="180" value="CursivePilot test"></div><div class="field"><label for="compat-style">Style</label><select id="compat-style" data-compat-style></select></div></div><div class="compat-output" data-compat-output></div><div class="control-row"><button class="button button-primary" type="button" data-compat-copy>Copy test text</button></div><p class="status" data-status aria-live="polite"></p><h3>Layout previews</h3><p class="helper">These cards simulate layout size only. They do not claim to reproduce another platform's font engine.</p><div class="preview-grid"><div class="platform-preview"><strong>Short profile line</strong><span data-preview-text></span></div><div class="platform-preview"><strong>Caption line</strong><span data-preview-text></span></div><div class="platform-preview"><strong>Chat message</strong><span data-preview-text></span></div><div class="platform-preview"><strong>Display name</strong><span data-preview-text></span></div></div></div></div></div></section><section class="section"><div class="shell content-grid"><article class="article"><h2>Why Unicode cursive compatibility has to be tested in the destination</h2><p>Copyable cursive is Unicode text. Final glyphs are selected by the fonts and rules available on the receiving operating system, browser or app, so a browser preview cannot certify every third-party platform.</p><h2>A reliable test method</h2><ol><li>Use a sample containing uppercase, lowercase, numbers and punctuation.</li><li>Copy the generated string.</li><li>Paste it into the exact field and app you plan to use.</li><li>Check another device if your audience uses multiple platforms.</li><li>If any glyph fails, try Script, Italic or ordinary text.</li></ol><h2>What we do not claim</h2><p>CursivePilot does not publish “100% compatible” badges for third-party apps without direct evidence. Platform support can change independently of this site. The checker is designed to make your own verification faster and more transparent.</p></article><aside class="aside-card"><h2>Related</h2><a href="/cursive-generator/">Cursive generator</a><a href="/guides/unicode-cursive-vs-fonts/">Unicode vs fonts guide</a></aside></div></section>`
};

const howItWorks={
 path:'/how-it-works/',title:`How ${site.name} Works – Privacy, Output Types & Limits`,
 description:`Learn how ${site.name} creates copyable cursive, handwriting, calligraphy, signatures and worksheets.`,
 breadcrumbs:crumbs('How It Works','/how-it-works/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><span class="eyebrow">Transparent by design</span><h1>How the tools work</h1><p class="lede">CursivePilot separates copyable Unicode from rendered visual lettering so you know exactly what output you are creating.</p><h2>Browser-side processing</h2><p>Cursive conversion uses JavaScript character mapping. Handwriting, calligraphy, signature and worksheet tools draw onto HTML canvas elements. Generator text is processed on the device rather than sent to a handwriting AI service.</p><h2>Web fonts</h2><p>Visual tools request selected font files from Google Fonts. Those font requests are separate from the generator text itself.</p><h2>Favorites and local storage</h2><p>The Cursive Generator can remember favorite styles in your browser using local storage. That preference stays on the device unless you clear browser data.</p><h2>About AI claims</h2><p>The current version does not clone a person's handwriting with machine learning. We describe the technology as Unicode conversion, fonts and browser rendering rather than calling those features AI.</p><h2>Contact submissions</h2><p>The optional contact form is processed by Netlify Forms so the site owner can review messages. The generators themselves do not require an account or database.</p></article><aside class="aside-card"><h2>Policies</h2><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/about/">About</a></aside></div></section>`
};

const about={
 path:'/about/',title:`About ${site.name} – Focused Cursive & Handwriting Tools`,
 description:`${site.name} is a focused collection of browser-based cursive, handwriting, calligraphy, signature and worksheet tools.`,
 breadcrumbs:crumbs('About','/about/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><span class="eyebrow">About the project</span><h1>An independent writing-tool project</h1><p class="lede">${site.name} focuses on one job family: turning typed words into useful script, handwriting and practice outputs without forcing an account.</p><h2>Editorial approach</h2><p>We explain what each tool actually does, including limitations. We do not label simple Unicode conversion or font rendering as AI, and we avoid claiming compatibility with third-party platforms unless it can be verified.</p><h2>How pages are reviewed</h2><p>Tool instructions and technical guides are reviewed for consistency with the implementation. Search-facing content is written to answer the user's task rather than to create near-duplicate keyword pages.</p><h2>Current review</h2><p>Site content and SEO implementation were reviewed by CursivePilot Editorial on September 27, 2026.</p></article><aside class="aside-card"><h2>Transparency</h2><a href="/how-it-works/">How it works</a><a href="/cursive-text-compatibility/">Compatibility Lab</a><a href="/privacy/">Privacy</a></aside></div></section>`
};

const privacy={
 path:'/privacy/',title:`Privacy Policy | ${site.name}`,
 description:`Privacy information for ${site.name}, including browser-side processing, web font requests and contact form data.`,
 breadcrumbs:crumbs('Privacy','/privacy/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><h1>Privacy Policy</h1><p class="lede">CursivePilot is designed so the core writing tools work without an account or database.</p><p class="article-meta">Effective September 27, 2026</p><h2>Generator input</h2><p>Text entered into the generators is processed in your browser by the site's JavaScript and canvas code. The current version does not send generator text to a handwriting model or CursivePilot database.</p><h2>Favorite styles</h2><p>If you favorite a cursive style, that preference is stored in your browser's local storage and is not synced to an account.</p><h2>Web fonts</h2><p>Some visual tools load font resources from Google Fonts. Your browser may connect to Google's font services to retrieve those files.</p><h2>Contact form</h2><p>If you submit the contact form, the information you enter is processed by Netlify Forms so the site owner can receive and review the message.</p><h2>Hosting and technical logs</h2><p>The site is hosted on Netlify, whose infrastructure may process routine request information needed to deliver and secure the site.</p><h2>Analytics and advertising</h2><p>No analytics or advertising tag is enabled by the source code unless a valid Google Tag Manager ID is configured for deployment.</p></article><aside class="aside-card"><h2>Related</h2><a href="/how-it-works/">How it works</a><a href="/terms/">Terms</a><a href="/contact/">Contact</a></aside></div></section>`
};

const terms={
 path:'/terms/',title:`Terms of Use | ${site.name}`,
 description:`Terms for using ${site.name}'s cursive, handwriting, calligraphy, signature and worksheet tools.`,
 breadcrumbs:crumbs('Terms','/terms/'),
 content:`<section class="section"><div class="shell content-grid"><article class="article"><h1>Terms of Use</h1><p class="lede">By using CursivePilot, you agree to use the tools lawfully and to review generated output before relying on it.</p><p class="article-meta">Effective September 27, 2026</p><h2>Permitted use</h2><p>You may use the tools for lawful personal, educational and design purposes. You are responsible for ensuring that your use complies with applicable rules and third-party rights.</p><h2>Signature-style output</h2><p>The signature generator creates decorative name lettering. It does not verify identity, consent, authorship or legal validity.</p><h2>Compatibility and availability</h2><p>Unicode rendering, browser behavior, fonts and third-party platforms can change. CursivePilot does not guarantee that every style will display identically everywhere.</p><h2>No warranty</h2><p>The tools are provided on an as-available basis. Review exports, print previews and copied text before using them in important work.</p><h2>Abuse</h2><p>Do not use the service to impersonate another person, misrepresent authorization, violate intellectual-property rights or support unlawful activity.</p></article><aside class="aside-card"><h2>Related</h2><a href="/privacy/">Privacy</a><a href="/how-it-works/">How it works</a><a href="/contact/">Contact</a></aside></div></section>`
};

const contact={
 path:'/contact/',title:`Contact ${site.name}`,
 description:`Contact ${site.name} with a bug report, compatibility issue or feature suggestion.`,
 breadcrumbs:crumbs('Contact','/contact/'),
 content:`<section class="section"><div class="shell contact-grid"><div><span class="eyebrow">Contact</span><h1>Contact CursivePilot</h1><p class="lede">Send a bug report, compatibility issue or focused feature suggestion.</p>${site.email ? `<p>Support email: <strong>${site.email}</strong></p>` : ''}</div><form class="form-card" name="contact" method="POST" action="/thanks/" data-netlify="true" netlify-honeypot="website"><input type="hidden" name="form-name" value="contact"><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="field"><label for="contact-email">Email (optional)</label><input id="contact-email" name="email" type="email" maxlength="200"></div><div class="field" style="margin-top:14px"><label for="contact-message">Message</label><textarea id="contact-message" name="message" minlength="10" maxlength="4000" required></textarea></div><button class="button button-primary" style="margin-top:14px" type="submit">Send message</button><p class="helper">This form is handled by Netlify Forms. No account is required.</p></form></div></section>`
};

const thanks={
 path:'/thanks/',title:`Message Sent | ${site.name}`,
 description:'Thanks for contacting CursivePilot.',
 noindex:true,
 breadcrumbs:crumbs('Message Sent','/thanks/'),
 content:`<section class="section"><div class="shell"><span class="eyebrow">Message sent</span><h1>Thanks for the feedback.</h1><p class="lede">Your message was submitted successfully.</p><div class="hero-actions"><a class="button button-primary" href="/cursive-generator/">Back to Cursive Generator</a><a class="button button-secondary" href="/">Home</a></div></div></section>`
};

export const pages=[home,cursive,handwriting,calligraphy,signature,worksheet,alphabet,guideUnicode,guidePractice,compatibility,howItWorks,about,privacy,terms,contact,thanks];
